{
 "title": "Prellblock",
 "description": "Prellblock Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Block Number",
   "type": "stat",
   "description": "The block number of the blockchain.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "world_state_block_number", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Turi Received Transactions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "turi_num_received_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Turi Received Invalid Transactions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "turi_num_received_invalid_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PRaftBFT Queue Backlog",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "praftbft_queue_backlog", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Turi Incoming TPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(turi_num_received_txs[5s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time To Block Storage (95th percentile)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(blockstorage_arrival_time_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Time To Block Storage (99th percentile)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(blockstorage_arrival_time_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Block Storage TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(block_storage_num_txs[5s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Time to BlockStorage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "blockstorage_arrival_time_sum/blockstorage_arrival_time_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DataStorage disk size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "datastorage_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "BlockStorage disk size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "blockstorage_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Time To BlockStorage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(blockstorage_arrival_time_bucket[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time To BlockStorage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blockstorage_arrival_time_bucket[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time To DataStorage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(datastorage_arrival_time_bucket[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PRaftBFT residence time in queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(praftbft_queue_residence_time_bucket[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PRaftBFT LederTerm",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "praftbft_leader_term", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PRaftBFT last Leader Term change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "praftbft_leader_term_change * 1000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PRaftBFT last  Prepare message",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "praftbft_last_prepare_message * 1000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PRaftBFT last  Append message",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "praftbft_last_append_message * 1000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PRaftBFT last  Commit message",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "praftbft_last_commit_message * 1000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}